---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install php support
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_disribution == "Ubuntu"
