---

- hosts: all
  become: true
  gather_facts: true
  pre_tasks:

  - name: install updates OracleLinux
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'OracleLinux'

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'


- hosts: web_servers
  become: true 
  tasks:  

  - name: install apache and php package for Ubuntu
    tags: apache,apache2,ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'


  - name: install apache and php package for OracleLinux
    tags: apache,oraclelinux,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'OracleLinux'

  - name: copy default html file to site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts : db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: ubuntu,mariadb,db
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: install mariadb package (Oracle)
    tags: oraclelinux,mariadb,db
    dnf:
      name:
       - mariadb-server
      state: latest
    when: ansible_distribution == 'OracleLinux'

- hosts : file_servers
  become : true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
